# Generated by Django 6.0.2 on 2026-06-06 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_existing_user_roles(apps, schema_editor):
    """Preserve role intent from the legacy boolean fields."""
    User = apps.get_model('core', 'User')
    for user in User.objects.all():
        if user.is_staff or user.is_superuser:
            user.role = 'admin'
        elif user.is_tutor:
            user.role = 'tutor'
        else:
            user.role = 'student'
        user.save(update_fields=['role'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contactmessage_sitestatistic'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_suspended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('tutor', 'Tutor'), ('student', 'Student')], default='student', max_length=20),
        ),
        migrations.RunPython(migrate_existing_user_roles, migrations.RunPython.noop),
        migrations.CreateModel(
            name='TutorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(blank=True, max_length=255)),
                ('county', models.CharField(blank=True, max_length=100)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=255)),
                ('registration_number', models.CharField(max_length=100)),
                ('must_change_password', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provisioned_students', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tutor', 'registration_number'), name='unique_student_registration_per_tutor')],
            },
        ),
    ]
