# Generated by Django 6.0.2 on 2026-06-06 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_is_suspended_user_phone_number_user_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='classroom',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='password',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
