# Generated by Django 6.0.2 on 2026-06-07 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_submission_options_studentanswer_awarded_marks_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proctorlog',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='exam',
            name='auto_disqualify_on_violation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exam',
            name='auto_submit_on_violation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exam',
            name='detect_fullscreen_exit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exam',
            name='detect_refresh',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exam',
            name='detect_tab_switch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exam',
            name='detect_window_blur',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exam',
            name='disable_copy_paste',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exam',
            name='disable_right_click',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exam',
            name='disable_text_selection',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exam',
            name='max_violation_warnings',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='exam',
            name='proctoring_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exam',
            name='require_fullscreen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proctorlog',
            name='details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='proctorlog',
            name='submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proctor_logs', to='core.submission'),
        ),
        migrations.AddField(
            model_name='proctorlog',
            name='triggered_disqualification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proctorlog',
            name='violation_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='submission',
            name='disqualification_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='disqualified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='is_disqualified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='proctorlog',
            name='violation_type',
            field=models.CharField(choices=[('TAB_SWITCH', 'Left Page/Tab'), ('WINDOW_BLUR', 'Window Lost Focus'), ('COPY', 'Attempted Copy'), ('PASTE', 'Attempted Paste'), ('CONTEXT_MENU', 'Attempted Right Click'), ('TEXT_SELECTION', 'Attempted Text Selection'), ('FULLSCREEN_EXIT', 'Exited Fullscreen'), ('REFRESH', 'Refresh/Reload Attempt'), ('MULTIPLE_SESSION', 'Possible Multiple Session')], max_length=50),
        ),
    ]
