from django.urls import path
from . import views

urlpatterns = [
    # The Homepage
    path('', views.index, name='index'),
    path('portal/', views.portal_landing, name='portal_landing'),
    
    # The AJAX Contact Form Endpoint
    path('send-message/', views.send_message, name='send_message'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('dashboard/admin/', views.admin_dashboard, name='admin_dashboard'),
    path('dashboard/admin/users/', views.admin_users, name='admin_users'),
    path('dashboard/admin/users/<int:user_id>/action/', views.admin_user_action, name='admin_user_action'),
    path('dashboard/admin/billing/', views.admin_billing, name='admin_billing'),
    path('dashboard/admin/billing/invoices/<int:invoice_id>/action/', views.admin_invoice_action, name='admin_invoice_action'),
    path('dashboard/admin/plans/', views.admin_plans, name='admin_plans'),
    path('dashboard/admin/plans/<int:plan_id>/edit/', views.admin_plans, name='admin_plan_edit'),
    path('dashboard/admin/contacts/', views.admin_contacts, name='admin_contacts'),
    path('dashboard/admin/contacts/<int:contact_id>/action/', views.admin_contact_action, name='admin_contact_action'),
    path('dashboard/admin/support/new/', views.admin_support_issue, name='admin_support_issue_create'),
    path('dashboard/admin/support/<int:issue_id>/edit/', views.admin_support_issue, name='admin_support_issue_edit'),
    path('dashboard/admin/announcements/', views.admin_announcements, name='admin_announcements'),
    path('dashboard/admin/announcements/<int:announcement_id>/edit/', views.admin_announcements, name='admin_announcement_edit'),
    path('dashboard/admin/audit-logs/', views.admin_audit_logs, name='admin_audit_logs'),
    path('dashboard/admin/background-jobs/', views.admin_background_jobs, name='admin_background_jobs'),
    path('dashboard/admin/background-jobs/dispatch/', views.admin_dispatch_background_job, name='admin_dispatch_background_job'),
    path('dashboard/tutor/', views.tutor_dashboard, name='tutor_dashboard'),
    path('dashboard/tutor/classrooms/<int:classroom_id>/', views.classroom_detail, name='classroom_detail'),
    path('dashboard/tutor/classrooms/<int:classroom_id>/edit/', views.classroom_edit, name='classroom_edit'),
    path('dashboard/tutor/classrooms/<int:classroom_id>/archive/', views.classroom_archive, name='classroom_archive'),
    path('dashboard/tutor/assessments/', views.assessment_list, name='assessment_list'),
    path('dashboard/tutor/assessments/new/', views.assessment_create, name='assessment_create'),
    path('dashboard/tutor/assessments/<int:exam_id>/', views.assessment_detail, name='assessment_detail'),
    path('dashboard/tutor/assessments/<int:exam_id>/edit/', views.assessment_edit, name='assessment_edit'),
    path('dashboard/tutor/assessments/<int:exam_id>/sections/add/', views.assessment_add_section, name='assessment_add_section'),
    path('dashboard/tutor/assessments/<int:exam_id>/questions/add/', views.assessment_add_question, name='assessment_add_question'),
    path('dashboard/tutor/assessments/<int:exam_id>/questions/import/', views.assessment_import_questions, name='assessment_import_questions'),
    path('dashboard/tutor/assessments/<int:exam_id>/questions/from-bank/', views.assessment_add_from_bank, name='assessment_add_from_bank'),
    path('dashboard/tutor/assessments/<int:exam_id>/publish/', views.assessment_publish, name='assessment_publish'),
    path('dashboard/tutor/reports/', views.tutor_reports, name='tutor_reports'),
    path('dashboard/tutor/reports/classrooms/<int:classroom_id>/', views.classroom_report, name='classroom_report'),
    path('dashboard/tutor/reports/assessments/<int:exam_id>/', views.assessment_report, name='assessment_report'),
    path('dashboard/tutor/reports/assessments/<int:exam_id>/export/', views.assessment_report_export, name='assessment_report_export'),
    path('dashboard/tutor/reports/assessments/<int:exam_id>/export.xlsx/', views.assessment_report_excel_export, name='assessment_report_excel_export'),
    path('dashboard/tutor/billing/', views.billing_overview, name='billing_overview'),
    path('dashboard/tutor/billing/subscriptions/', views.subscription_plans, name='subscription_plans'),
    path('dashboard/tutor/billing/subscriptions/<int:plan_id>/start/', views.start_subscription, name='start_subscription'),
    path('dashboard/tutor/billing/invoices/<int:invoice_id>/', views.invoice_detail, name='invoice_detail'),
    path('dashboard/tutor/billing/invoices/<int:invoice_id>/mpesa/', views.invoice_start_mpesa, name='invoice_start_mpesa'),
    path('dashboard/tutor/billing/invoices/<int:invoice_id>/dev-confirm/', views.invoice_dev_confirm, name='invoice_dev_confirm'),
    path('payments/mpesa/stk-callback/', views.mpesa_stk_callback, name='mpesa_stk_callback'),
    path('payments/mpesa/c2b-confirmation/', views.mpesa_c2b_confirmation, name='mpesa_c2b_confirmation'),
    path('dashboard/tutor/students/<int:student_id>/reset-credentials/', views.reset_student_credentials_view, name='reset_student_credentials'),
    path('dashboard/student/', views.student_dashboard, name='student_dashboard'),
    path('dashboard/student/reports/', views.student_reports, name='student_reports'),
    path('dashboard/student/assessments/<int:exam_id>/start/', views.student_assessment_start, name='student_assessment_start'),
    path('dashboard/student/attempts/<int:submission_id>/', views.student_assessment_take, name='student_assessment_take'),
    path('dashboard/student/attempts/<int:submission_id>/result/', views.student_assessment_result, name='student_assessment_result'),
    path('dashboard/student/attempts/<int:submission_id>/proctor-violation/', views.student_proctor_violation, name='student_proctor_violation'),
    
    # Placeholder for other links in your index.html (Classrooms, Exams, etc)
    # path('classrooms/', views.classroom_list, name='classroom_list'),
]
